import { TELEFONICA_SKIN } from './constants';
import {applyAlpha} from '../utils/color';

import type {GetKnownSkin, KnownSkin} from './types';
import { tokenfigma } from '../../hooks/tokenfigma';
import { jsonFigma } from './tokens';

export const setJson = () => {
  const responseToken = jsonFigma;
  const colores = responseToken.Color;
  const tipografia = responseToken['Tipografía App'];
  return {
    colores,
    tipografia
  }
};

export const getTelefonicaSkin: any = () => {
    const token = setJson();
    const colores = token.colores['Colores Mística-CL - React'];
    const skin: KnownSkin = {
      name: TELEFONICA_SKIN,
      colors: {
        appBarBackground: colores.Background.appBarBackground.value,
        background: colores.Background.appBarBackground.value,
        backgroundContainer: colores.Background.appBarBackground.value,
        backgroundContainerHover: applyAlpha(colores.Background.backgroundContainerHover.value, 0.03),
        backgroundContainerPressed: applyAlpha(colores.Background.backgroundContainerHover.value, 0.05),
        backgroundContainerBrand: colores.Background.backgroundContainerBrandHover.value,
        backgroundContainerBrandHover: applyAlpha(colores.Background.backgroundContainerBrandHover.value, 0.2),
        backgroundContainerBrandPressed: applyAlpha(colores.Background.backgroundContainerBrandPressed.value, 0.4),
        backgroundContainerBrandOverInverse: colores.Background.backgroundContainerBrandOverInverse.value,
        backgroundContainerAlternative: colores.Background.backgroundContainerAlternative.value,
        backgroundBrand: colores.Background.backgroundBrand.value,
        backgroundBrandSecondary: colores.Background.backgroundBrandSecondary.value,
        backgroundOverlay: applyAlpha(colores.Background.backgroundOverlay.value, 0.8),
        backgroundSkeleton: colores.Background.backgroundSkeleton.value,
        backgroundSkeletonInverse: colores.Background.backgroundSkeletonInverse.value,
        navigationBarBackground: colores.Background.navigationBarBackground.value,
        backgroundAlternative: colores.Background.backgroundAlternative.value,
        backgroundFeedbackBottom: colores.Background.backgroundFeedbackBottom.value,
        skeletonWave: colores.Background.SkeletonWave.value,
        borderLow: colores.Borders.borderLow.value,
        border: colores.Borders.border.value,
        borderHigh: colores.Borders.borderHigh.value,
        borderSelected: colores.Borders.borderSelected.value,
        coverBackgroundHover: applyAlpha(colores.Cover.coverBackgroundHover.value, 0.25),
        coverBackgroundPressed: applyAlpha(colores.Cover.CoverBackgroundPressed.value, 0.35),
        buttonDangerBackground: colores.Buttons.buttonDangerBackground.value,
        buttonDangerBackgroundSelected: colores.Buttons.buttonDangerBackgroundSelected.value,
        buttonDangerBackgroundHover: colores.Buttons.buttonDangerBackgroundSelected.value,
        buttonLinkBackgroundSelected: colores.Buttons.buttonLinkBackgroundSelected.value,
        buttonLinkBackgroundInverseSelected: applyAlpha(colores.Buttons.buttonLinkBackgorundInverseSelected.value, 0.08),
        buttonPrimaryBackground: colores.Buttons.buttonPirmaryBackground.value,
        buttonPrimaryBackgroundInverse: colores.Buttons.buttonPrimaryBackgroundInverse.value,
        buttonPrimaryBackgroundSelected: colores.Buttons.buttonPrimaryBackgroundSelected.value,
        buttonPrimaryBackgroundHover: colores.Buttons.buttonPrimaryBackgroundHover.value,
        buttonPrimaryBackgroundInverseSelected: colores.Buttons.buttonPrimaryBackgroundInverseSelected.value,
        buttonSecondaryBorder: colores.Buttons.buttonSecundaryBorder.value,
        buttonSecondaryBorderSelected: colores.Buttons.butonSecundaryBorderSelected.value,
        buttonSecondaryBackgroundHover: colores.Texts.Global.textSecondaryInverse.value,
        buttonSecondaryBackgroundSelected: colores.Texts.Global.textSecondaryInverse.value,
        buttonSecondaryBorderInverse: colores.Background.appBarBackground.value,
        buttonSecondaryBorderInverseSelected: colores.Background.appBarBackground.value,
        buttonSecondaryBackgroundInverseHover: applyAlpha(colores.Buttons.buttonSecondaryBackgroundInverseHover.value, 0.1),
        buttonSecondaryBackgroundInverseSelected: applyAlpha(colores.Background.appBarBackground.value, 0.1),
        textButtonPrimary: colores.Texts.Buttons.textButtonPrimary.value,
        textButtonPrimaryInverse: colores.Texts.Buttons.textButtonPrimaryInverse.value,
        textButtonPrimaryInverseSelected: colores.Texts.Buttons.textButtonSecondary.value,
        textButtonSecondary: colores.Texts.Buttons.textButtonSecondary.value,
        textButtonSecondarySelected: colores.Texts.Buttons.textButtonSecondarySelected.value,
        textButtonSecondaryInverse: colores.Texts.Buttons.textButtonSecondaryInverse.value,
        textButtonSecondaryInverseSelected: colores.Texts.Buttons.textButtonSecondaryInverseSelected.value,
        textLink: colores.Texts.Buttons.textLink.value,
        textLinkInverse: colores.Texts.Buttons.textLinkInverse.value,
        textLinkDanger: colores.Texts.Buttons.textLinkDanger.value,
        textLinkSnackbar: colores.Texts.Buttons.TextLinkSnackbar.value,
        control: colores.Controls.Control.value,
        controlActivated: colores.Controls.ControlActivated.value,
        controlError: colores.Controls.ControlError.value,
        loadingBar: colores.Controls.loadingBar.value,
        loadingBarBackground: colores.Controls.loadingBarBackground.value,
        toggleAndroidInactive: colores.Controls.toggleAndroidInactive.value,
        toggleAndroidBackgroundActive: colores.Controls.toggleAndroidBackgroundActive.value,
        iosControlKnob: colores.Controls.iosControlKnob.value,
        divider: colores.Divider.divider.value,
        dividerInverse: applyAlpha(colores.Divider.dividerInverse.value, 0.2),
        navigationBarDivider: colores.Divider.navigationBarDivider.value,
        badge: colores.Feedbacks.Badge.value,
        feedbackErrorBackground: colores.Feedbacks.feedbackErrorBackground.value,
        feedbackInfoBackground: colores.Feedbacks.FeedbackInfoBackground.value,
        brand: colores.Global.brand.value,
        brandHigh: colores.Global.brandHigh.value,
        inverse: colores.Global.inverse.value,
        neutralHigh: colores.Global.neutralHigh.value,
        neutralMedium: colores.Global.neutralMedium.value,
        neutralMediumInverse: colores.Global.neutralMediumInverse.value,
        neutralLow: colores.Global.neutralLow.value,
        neutralLowAlternative: colores.Global.neutralLowAlternative.value,
        textPrimary: colores.Texts.Global.textPrimary.value,
        textPrimaryInverse: colores.Texts.Global.textPrimaryInverse.value,
        textSecondary: colores.Texts.Global.textSecondary.value,
        textSecondaryInverse: colores.Texts.Global.textSecondaryInverse.value,
        error: colores.Global.error.value,
        success: colores.Global.success.value,
        warning: colores.Global.warning.value,
        promo: colores.Global.promo.value,
        highlight: colores.Global.higlight.value,
        successLow: colores.Global.successLow.value,
        warningLow: colores.Global.warningLow.value,
        errorLow: colores.Global.errorLow.value,
        promoLow: colores.Global.promoLow.value,
        brandLow: colores.Global.brandLow.value,
        successHigh: colores.Global.successHigh.value,
        warningHigh: colores.Global.warningHigh.value,
        errorHigh: colores.Global.errorHigh.value,
        promoHigh: colores.Global.promoHigh.value,
        successHighInverse: colores.Global.successHighInverse.value,
        warningHighInverse: colores.Global.warningHighInverse.value,
        errorHighInverse: colores.Global.errorHighInverse.value,
        promoHighInverse: colores.Global.PromoHighInverse.value,
        textNavigationBarPrimary: colores.Texts['Bar Texts'].textNavigationBarPrimary.value,
        textNavigationBarSecondary: colores.Texts['Bar Texts'].TextNavigationBarSecondary.value,
        textNavigationSearchBarHint: colores.Texts['Bar Texts'].textNavigationSearchBarHint.value,
        textNavigationSearchBarText: colores.Texts['Bar Texts'].textNavigationSearchBarText.value,
        textAppBar: colores.Texts['Bar Texts'].textAppBar.value,
        textAppBarSelected: colores.Texts['Bar Texts'].textAppBarSelected.value,
        customTabsBackground: colores.Texts['Bar Texts'].textAppBarSelected.value,
      },
      darkModeColors: {
        background: colores.Background.background.value,
        backgroundAlternative: colores.Background.backgroundAlternative.value,
        backgroundBrand: colores.Background.backgroundBrand.value,
        backgroundBrandSecondary: colores.Background.backgroundBrandSecondary.value,
        backgroundContainer: colores.Background.backgroundContainer.value,
        backgroundContainerHover: applyAlpha(colores.Background.backgroundContainerHover.value, 0.03),
        backgroundContainerPressed: applyAlpha(colores.Background.backgroundContainerHover.value, 0.05),
        backgroundContainerBrand: colores.Background.backgroundContainerBrand.value,
        backgroundContainerBrandHover: applyAlpha(colores.Background.backgroundContainerBrandHover.value, 0.03),
        backgroundContainerBrandPressed: applyAlpha(colores.Background.backgroundContainerBrandPressed.value, 0.05),
        backgroundContainerBrandOverInverse: colores.Background.backgroundContainerBrandOverInverse.value,
        backgroundContainerAlternative: colores.Background.backgroundContainerAlternative.value,
        backgroundOverlay: applyAlpha(colores.Background.backgroundOverlay.value, 0.8),
        backgroundSkeleton: colores.Background.backgroundSkeleton.value,
        backgroundSkeletonInverse: colores.Background.backgroundSkeletonInverse.value,
        backgroundFeedbackBottom: colores.Background.backgroundFeedbackBottom.value,
        appBarBackground: colores.Background.appBarBackground.value,
        navigationBarBackground: colores.Background.navigationBarBackground.value,
        skeletonWave: colores.Background.SkeletonWave.value,
        borderLow: colores.Borders.borderLow.value,
        border: colores.Borders.border.value,
        borderHigh: colores.Borders.borderHigh.value,
        borderSelected: colores.Borders.borderSelected.value,
        coverBackgroundHover: applyAlpha(colores.Cover.coverBackgroundHover.value, 0.25),
        coverBackgroundPressed: applyAlpha(colores.Cover.CoverBackgroundPressed.value, 0.35),
        buttonDangerBackground: colores.Buttons.buttonDangerBackground.value,
        buttonDangerBackgroundSelected: colores.Buttons.buttonDangerBackgroundSelected.value,
        buttonDangerBackgroundHover: colores.Buttons.buttonDangerBackgroundHover.value,
        buttonLinkBackgroundSelected: applyAlpha(colores.Buttons.buttonLinkBackgroundSelected.value, 0.08),
        buttonLinkBackgroundInverseSelected: applyAlpha(colores.Buttons.buttonLinkBackgorundInverseSelected.value, 0.08),
        buttonPrimaryBackground: colores.Buttons.buttonPirmaryBackground.value,
        buttonPrimaryBackgroundInverse: colores.Buttons.buttonPrimaryBackgroundInverse.value,
        buttonPrimaryBackgroundSelected: colores.Buttons.buttonPrimaryBackgroundSelected.value,
        buttonPrimaryBackgroundHover: colores.Buttons.buttonPrimaryBackgroundHover.value,
        buttonPrimaryBackgroundInverseSelected: colores.Buttons.buttonPrimaryBackgroundInverseSelected.value,
        buttonSecondaryBackgroundSelected: applyAlpha(colores.Buttons.buttonSecundaryBackgroundSelected.value, 0.15),
        buttonSecondaryBorder: colores.Buttons.buttonSecundaryBorder.value,
        buttonSecondaryBackgroundHover: applyAlpha(colores.Buttons.buttonSecundaryBackgroundSelected.value, 0.15),
        buttonSecondaryBorderSelected: colores.Buttons.butonSecundaryBorderSelected.value,
        buttonSecondaryBorderInverse: colores.Buttons.buttonSecundaryBorderInverse.value,
        buttonSecondaryBorderInverseSelected: colores.Buttons.buttonSecundaryBorderInverse.value,
        buttonSecondaryBackgroundInverseHover: applyAlpha(colores.Buttons.buttonSecondaryBackgroundInverseHover.value, 0.15),
        buttonSecondaryBackgroundInverseSelected: applyAlpha(colores.Buttons.buttonSecundaryBackgroundInverseSelected.value, 0.15),
        textButtonPrimary: colores.Texts.Buttons.textButtonPrimary.value,
        textButtonPrimaryInverse: colores.Texts.Buttons.textButtonPrimaryInverse.value,
        textButtonPrimaryInverseSelected: colores.Texts.Buttons.textButtonSecondary.value,
        textButtonSecondary: colores.Texts.Buttons.textButtonSecondary.value,
        textButtonSecondarySelected: colores.Texts.Buttons.textButtonSecondarySelected.value,
        textButtonSecondaryInverse: colores.Texts.Buttons.textButtonSecondaryInverse.value,
        textButtonSecondaryInverseSelected: colores.Texts.Buttons.textButtonSecondaryInverseSelected.value,
        textLink: colores.Texts.Buttons.textLink.value,
        textLinkInverse: colores.Texts.Buttons.textLinkInverse.value,
        textLinkDanger: colores.Texts.Buttons.textLinkDanger.value,
        textLinkSnackbar: colores.Texts.Buttons.TextLinkSnackbar.value,
        control: colores.Controls.Control.value,
        controlActivated: colores.Controls.ControlActivated.value,
        controlError: colores.Controls.ControlError.value,
        loadingBar: colores.Controls.loadingBar.value,
        loadingBarBackground: colores.Controls.loadingBarBackground.value,
        toggleAndroidInactive: colores.Controls.toggleAndroidInactive.value,
        toggleAndroidBackgroundActive: colores.Controls.toggleAndroidBackgroundActive.value,
        iosControlKnob: colores.Controls.iosControlKnob.value,
        divider: applyAlpha(colores.Divider.divider.value, 0.05),
        dividerInverse: applyAlpha(colores.Divider.dividerInverse.value, 0.05),
        navigationBarDivider: colores.Divider.navigationBarDivider.value,
        badge: colores.Feedbacks.Badge.value,
        feedbackErrorBackground: colores.Feedbacks.feedbackErrorBackground.value,
        feedbackInfoBackground: colores.Feedbacks.FeedbackInfoBackground.value,
        brand: colores.Global.brand.value,
        brandHigh: applyAlpha(colores.Global.brandHigh.value, 0.05),
        inverse: colores.Global.inverse.value,
        neutralHigh: colores.Global.neutralHigh.value,
        neutralMedium: colores.Global.neutralMedium.value,
        neutralMediumInverse: colores.Global.neutralMediumInverse.value,
        neutralLow: colores.Global.neutralLow.value,
        neutralLowAlternative: colores.Global.neutralLowAlternative.value,
        textPrimary: colores.Texts.Global.textPrimary.value,
        textPrimaryInverse: colores.Texts.Global.textPrimaryInverse.value,
        textSecondary: colores.Texts.Global.textSecondary.value,
        textSecondaryInverse: colores.Texts.Global.textSecondaryInverse.value,
        error: colores.Global.error.value,
        success: colores.Global.success.value,
        warning: colores.Global.warning.value,
        promo: colores.Global.promo.value,
        highlight: colores.Global.higlight.value,
        successLow: colores.Global.successLow.value,
        warningLow: colores.Global.warningLow.value,
        errorLow: colores.Global.errorLow.value,
        promoLow: colores.Global.promoLow.value,
        brandLow: colores.Global.brandLow.value,
        successHigh: colores.Global.successHigh.value,
        warningHigh: colores.Global.warningHigh.value,
        errorHigh: colores.Global.errorHigh.value,
        promoHigh: colores.Global.promoHigh.value,
        successHighInverse: colores.Global.successHighInverse.value,
        warningHighInverse: colores.Global.warningHighInverse.value,
        errorHighInverse: colores.Global.errorHighInverse.value,
        promoHighInverse: colores.Global.PromoHighInverse.value,
        textNavigationBarPrimary: colores.Texts['Bar Texts'].textNavigationBarPrimary.value,
        textNavigationBarSecondary: colores.Texts['Bar Texts'].TextNavigationBarSecondary.value,
        textNavigationSearchBarHint: colores.Texts['Bar Texts'].textNavigationSearchBarHint.value,
        textNavigationSearchBarText: colores.Texts['Bar Texts'].textNavigationSearchBarText.value,
        textAppBar: colores.Texts['Bar Texts'].textAppBar.value,
        textAppBarSelected: colores.Texts['Bar Texts'].textAppBarSelected.value,
        customTabsBackground: colores.Texts['Bar Texts'].textAppBarSelected.value,
      },
      borderRadii: {
        avatar: '50%',
        bar: '0px',
        button: '999px',
        checkbox: '0px',
        container: '0px',
        indicator: '999px',
        input: '0px',
        legacyDisplay: '0px',
        popup: '0px',
        sheet: '8px',
      },
      textPresets: {
        cardTitle: {weight: 'regular'},
        text5: {weight: 'regular'},
        text6: {weight: 'regular'},
        text7: {weight: 'regular'},
        text8: {weight: 'regular'},
        text9: {weight: 'regular'},
        text10: {weight: 'regular'},
      },
    };
    return skin;
};
